// {
//     id: 2,
//     name: "Siti Nurhaliza",
//     email: "siti.nurhaliza@example.com",
//     notelepon: "081298765432",
//     password: "securepass456",
//     role: "pedagang",
//     namausaha: "Warung Siti",
//     alamatusaha: "Jl. Sudirman No. 45, Bandung",
//     category: "Makanan dan Minuman",
//     description: "Menyediakan makanan dan minuman ringan",
//     identitaspedagang: "KTP9876543210",
//     linkecommerences: null,
//     profilepict: "https://example.com/profile2.jpg",
//     isApproved: false
//   },
//   {
//     id: 3,
//     name: "Budi Santoso",
//     email: "budi.santoso@example.com",
//     notelepon: "081345678912",
//     password: "mypassword789",
//     role: "pedagang",
//     namausaha: "Budi Shop",
//     alamatusaha: "Jl. Gajah Mada No. 67, Surabaya",
//     category: null,
//     description: null,
//     identitaspedagang: "KTP5432109876",
//     linkecommerences: "https://shopee.co.id/budishop",
//     profilepict: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOG6E-AnifHE0PvMzIpCiDOZy1nWhJXXMZPg&s",
//     isApproved: true
//   },
//   {
//     id: 4,
//     name: "Rina Amelia",
//     email: "rina.amelia@example.com",
//     notelepon: "081223344556",
//     password: "rinasecure01",
//     role: "pedagang",
//     namausaha: "Amelia Mart",
//     alamatusaha: "Jl. Kartini No. 21, Yogyakarta",
//     category: "Fashion",
//     description: "Toko busana modern dan tradisional",
//     identitaspedagang: "KTP1122334455",
//     linkecommerences: "https://bukalapak.com/ameliamart",
//     profilepict: "https://example.com/profile3.jpg",
//     isApproved: false
//   },
//   {
//     id: 5,
//     name: "Andi Kurniawan",
//     email: "andi.kurniawan@example.com",
//     notelepon: "081333222444",
//     password: "andipassword123",
//     role: "pedagang",
//     namausaha: "Toko Kurnia",
//     alamatusaha: "Jl. Pahlawan No. 8, Medan",
//     category: "Alat Tulis",
//     description: "Menyediakan perlengkapan alat tulis lengkap",
//     identitaspedagang: "KTP2233445566",
//     linkecommerences: null,
//     profilepict: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOG6E-AnifHE0PvMzIpCiDOZy1nWhJXXMZPg&s",
//     isApproved: true
//   },
//   {
//     id: 6,
//     name: "Dewi Lestari",
//     email: "dewi.lestari@example.com",
//     notelepon: "081455667788",
//     password: "dewi!pass098",
//     role: "pedagang",
//     namausaha: "Lestari Snacks",
//     alamatusaha: "Jl. Mangga No. 45, Bali",
//     category: "Makanan dan Minuman",
//     description: "Distributor camilan khas Indonesia",
//     identitaspedagang: "KTP5566778899",
//     linkecommerences: "https://shopee.co.id/lestarisnacks",
//     profilepict: null,
//     isApproved: true
//   },
//   {
//     id: 7,
//     name: "Fajar Hidayat",
//     email: "fajar.hidayat@example.com",
//     notelepon: "081566778899",
//     password: "fajarsecure567",
//     role: "pedagang",
//     namausaha: "Hidayat Elektronik",
//     alamatusaha: "Jl. Cendrawasih No. 3, Makassar",
//     category: "Elektronik",
//     description: null,
//     identitaspedagang: "KTP6677889900",
//     linkecommerences: "https://tokopedia.com/hidayatelectronics",
//     profilepict: "https://example.com/profile4.jpg",
//     isApproved: false
//   },
//   {
//     id: 8,
//     name: "Samsul Arifin",
//     email: "samsul.arifin@example.com",
//     notelepon: "081677889900",
//     password: "samsul123pass",
//     role: "pedagang",
//     namausaha: "Arifin Hardware",
//     alamatusaha: "Jl. Rajawali No. 77, Semarang",
//     category: "Peralatan Rumah Tangga",
//     description: "Penyedia alat-alat rumah tangga terjangkau",
//     identitaspedagang: "KTP7788990011",
//     linkecommerences: null,
//     profilepict: null,
//     isApproved: true
//   },
//   {
//     id: 9,
//     name: "Lina Kusuma",
//     email: "lina.kusuma@example.com",
//     notelepon: "081788990011",
//     password: "linakusuma!pwd",
//     role: "pedagang",
//     namausaha: "Kusuma Books",
//     alamatusaha: "Jl. Diponegoro No. 19, Surabaya",
//     category: "Buku dan Stationery",
//     description: "Toko buku baru dan bekas",
//     identitaspedagang: "KTP8899001122",
//     linkecommerences: "https://bukalapak.com/kusumabooks",
//     profilepict: "https://example.com/profile5.jpg",
//     isApproved: false
//   },
//   {
//     id: 10,
//     name: "Bambang Supriyadi",
//     email: "bambang.supriyadi@example.com",
//     notelepon: "081899001122",
//     password: "bambangpass890",
//     role: "pedagang",
//     namausaha: "Supriyadi Tools",
//     alamatusaha: "Jl. Kenanga No. 50, Malang",
//     category: "Peralatan Bengkel",
//     description: null,
//     identitaspedagang: "KTP9900112233",
//     linkecommerences: "https://tokopedia.com/supriyaditools",
//     profilepict: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOG6E-AnifHE0PvMzIpCiDOZy1nWhJXXMZPg&s",
//     isApproved: true
//   }




  // const products = [
//     {
//       id: 1,
//       ownerId: 1,
//       name: "Produk 1",
//       images: [
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+1",
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+2",
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+3",
//       ],
//       price: "Rp 100.000",
//       shop: "Toko A",
//       description:
//         "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non dictum enim. Curabitur id magna enim. Donec eu tempus leo, ac vulputate massa. Integer nec luctus augue. Donec ullamcorper, ante eu tincidunt pulvinar, nisi purus condimentum mi, sit amet condimentum nibh lacus eget ex. Ut ac cursus nulla. Nulla in feugiat velit. Morbi suscipit enim at quam euismod egestas. Praesent ut suscipit ipsum. Donec diam lectus, semper id purus ut, scelerisque tincidunt nibh. Ut eros sem, pretium interdum velit ut, tempor gravida lacus. Ut feugiat venenatis odio eget dictum.",
//       category: "Kuliner",
//       link: "https://example.com/produk1",
//     },
//     {
//       id: 2,
//       ownerId: 2,
//       name: "Produk 2",
//       images: [
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+1",
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+2",
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+3",
//       ],
//       price: "Rp 100.000",
//       shop: "Toko B",
//       description:
//         "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non dictum enim. Curabitur id magna enim. Donec eu tempus leo, ac vulputate massa. Integer nec luctus augue. Donec ullamcorper, ante eu tincidunt pulvinar, nisi purus condimentum mi, sit amet condimentum nibh lacus eget ex. Ut ac cursus nulla. Nulla in feugiat velit. Morbi suscipit enim at quam euismod egestas. Praesent ut suscipit ipsum. Donec diam lectus, semper id purus ut, scelerisque tincidunt nibh. Ut eros sem, pretium interdum velit ut, tempor gravida lacus. Ut feugiat venenatis odio eget dictum.",
//       category: "Kuliner",
//       link: "https://example.com/produk1",
//     },
//     {
//       id: 3,
//       ownerId: 1,
//       name: "Produk 3",
//       images: [
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+1",
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+2",
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+3",
//       ],
//       price: "Rp 100.000",
//       shop: "Toko A",
//       description:
//         "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non dictum enim. Curabitur id magna enim. Donec eu tempus leo, ac vulputate massa. Integer nec luctus augue. Donec ullamcorper, ante eu tincidunt pulvinar, nisi purus condimentum mi, sit amet condimentum nibh lacus eget ex. Ut ac cursus nulla. Nulla in feugiat velit. Morbi suscipit enim at quam euismod egestas. Praesent ut suscipit ipsum. Donec diam lectus, semper id purus ut, scelerisque tincidunt nibh. Ut eros sem, pretium interdum velit ut, tempor gravida lacus. Ut feugiat venenatis odio eget dictum.",
//       category: "Fashion",
//       link: "https://example.com/produk1",
//     },
//     {
//       id: 4,
//       ownerId: 3,
//       name: "Produk 4",
//       images: [
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+1",
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+2",
//         "https://via.placeholder.com/300x200?text=Produk+1+Gambar+3",
//       ],
//       price: "Rp 100.000",
//       shop: "Toko A",
//       description:
//         "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non dictum enim. Curabitur id magna enim. Donec eu tempus leo, ac vulputate massa. Integer nec luctus augue. Donec ullamcorper, ante eu tincidunt pulvinar, nisi purus condimentum mi, sit amet condimentum nibh lacus eget ex. Ut ac cursus nulla. Nulla in feugiat velit. Morbi suscipit enim at quam euismod egestas. Praesent ut suscipit ipsum. Donec diam lectus, semper id purus ut, scelerisque tincidunt nibh. Ut eros sem, pretium interdum velit ut, tempor gravida lacus. Ut feugiat venenatis odio eget dictum.",
//       category: "Fashion",
//       link: "https://example.com/produk1",
//     },
//   ];


