name: Deploy Vite.js to EC2

on:
  push:
    branches:
      - staging
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run linting
    - name: Run ESLint
      run: npm run lint

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t pasarmalangan:latest .

    # Tag and push to ECR
    - name: Tag and push to ECR
      run: |
        docker tag pasarmalangan:latest 019476134787.dkr.ecr.us-east-1.amazonaws.com/pasarmalangan:latest
        docker push 019476134787.dkr.ecr.us-east-1.amazonaws.com/pasarmalangan:latest

    # Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull <ecr-repo-url>/pasarmalangan:latest
          docker-compose up -d viteapp
