name: CI/CD for Frontend (Vite.js)

on:
  push:
    branches:
      - main
      - staging
    paths:
      - "Frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (Frontend)
        run: npm install
        working-directory: ./Frontend

      # - name: Run linting (Frontend)
      #   run: npm run lint
      #   working-directory: ./Frontend

      # Build Vite.js project
      - name: Build Vite.js project
        run: npm run build
        working-directory: ./Frontend

      # Upload build output as artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: vite-build
          path: ./Frontend/dist

      # Build Docker image for Frontend
      - name: Build Docker image
        run: docker build -t koozee/pasarmalangan:latest -f Frontend/Dockerfile ./Frontend

      - name: Tag and push to Docker Hub
        run: |
          docker push koozee/pasarmalangan:latest

      - name: Deploy to EC2 (Frontend)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/pasarmalanganFE
            sudo docker pull koozee/pasarmalangan:latest
            sudo docker-compose up -d
