name: CI/CD for Frontend (Vite.js)

on:
  push:
    branches:
      - main
      - staging
    paths:
      - "Frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (Frontend)
        run: npm install
        working-directory: ./Frontend

      - name: Run linting (Frontend)
        run: npm run lint
        working-directory: ./Frontend

      - name: Build Docker image for Frontend
        run: docker build -t koozee/pasarmalangan:latest -f Frontend/Dockerfile .

      - name: Tag and push to Docker Hub
        run: |
          docker push koozee/pasarmalangan:latest

      - name: Deploy to EC2 (Frontend)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/pasarmalanganFE
            docker pull koozee/pasarmalangan:latest
            docker-compose up -d
